dataset_params:
  data_params:
    dataset_params:
      data_params:
        root: /path/to/CelebAMask-HQ/  # TODO
    image_size: 256
  mask_params:
    mask_root: gt_keep_masks
  batch_size: 16
  batch_size_val: 16
  batch_size_test: 16

args:  #guided_diffusion_params
  model_path: pretrained/celeba256_250000.pt  # TODO
  network_img_size: null

trainer_params:
  inference_mode: true
